import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-background`}>
                <Header />
                {children}
                <div className="bg-primaryMain w-full text-center mt-8 py-4">
                    &copy; Coprights 2024 | SITA
                </div>
            </body>
        </html>
    );
}
